### ISSUE TITLE
Object.getNotifier is not a function

### ISSUE THREAD

**Issue by xiongzhp** [srchea/pulse.js#2]

**Comment by xiongzhp** [comment]
Mac os, Google chrome 51.0.2704.103, when load pulse.html in /test in a local server environment.

**Comment by Mapaler** [comment]
Win10 + Firefox 51.01 or Chrome 55.0.2883.75 in Chinese.

**Comment by svenraju** [comment]
Same issue as Mabaler MacOS and latest chrome.

**Comment by infantilo** [comment]
hi! object.getNotifier and object.observe are deprecated and can't be used in all modern browser :-(
So these two function calls need to be rewritten using another trigger mechanism.
Maybe someone could get on this!?
