### ISSUE TITLE
Object.getNotifier is deprecated

### ISSUE THREAD

**Issue by ghost** [srchea/pulse.js#4]
I am hoping to use pulse to simply do bpm detection with the WebAudioAPI. I installed the project using bower, and made html file and pasted your README basic usage code as a script. In my console I get the error

> TypeError: Object.getNotifier is not a function

And upon further research I discovered that Object.getNotifier is deprecated. Is there an easy fix for this?

**Comment by srchea** [comment]
You may find [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) useful for this case. Let me know if you still have issues.

**Comment by srchea** [comment]
Fixed: https://github.com/srchea/pulse.js/pull/5
